"""drop username and organization_id from users

Revision ID: b68e4555c546
Revises: 6c7ea77d889e
Create Date: 2026-05-20 19:34:32.981778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b68e4555c546"
down_revision: Union[str, Sequence[str], None] = "6c7ea77d889e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_constraint(op.f("users_username_key"), "users", type_="unique")
    op.drop_column("users", "username")
    op.drop_column("users", "organization_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("organization_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "username", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.create_unique_constraint(
        op.f("users_username_key"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
