"""add slug and storefront_metadata to products

Revision ID: 3e809ecf0156
Revises: 934a8cb962c0
Create Date: 2026-05-20 03:22:31.166154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3e809ecf0156"
down_revision: Union[str, Sequence[str], None] = "934a8cb962c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("slug", sa.String(length=200), nullable=False))
    op.add_column(
        "products",
        sa.Column(
            "storefront_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_products_slug"), "products", ["slug"], unique=False)
    op.create_unique_constraint("uq_products_slug", "products", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_products_slug", "products", type_="unique")
    op.drop_index(op.f("ix_products_slug"), table_name="products")
    op.drop_column("products", "storefront_metadata")
    op.drop_column("products", "slug")
    # ### end Alembic commands ###
