set positional-arguments

runserver:
    uv run uvicorn app.main:app --reload

test *PYTEST_ARGS:
    if [ "${1:-}" = "--" ]; then shift; fi; uv run pytest "$@"

makemigrations message:
    uv run alembic revision --autogenerate -m "{{ message }}"

migrate:
    uv run alembic upgrade head
